
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both hardcoded values and environment variables
// This ensures the app works in both development and production
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://supabase-red-jacket.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1cGFiYXNlLXJlZC1qYWNrZXQiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTc0ODAzOTE4OCwiZXhwIjoyMDYzNjE1MTg4fQ.NPhmFr2C5g6xKnQw6P6lVlQlHKCwXw9j3F_EkTmXKF4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
