// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxpfrhufffomgkqluwrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4cGZyaHVmZmZvbWdrcWx1d3JnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDA4MTMsImV4cCI6MjA2MjM3NjgxM30.Bu3j78BI8Bq5RAJIdfr8q833nH1RkSQ-iny7K4yWRfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);